import port1 from "../img/portImages/maya-1.jpg";
import port2 from "../img/portImages/port1.jpg";
import port3 from "../img/portImages/port2.jpg";
import port4 from "../img/portImages/port3.jpg";
import port5 from "../img/portImages/port5.jpg";

const petProjects = [
  {
    id: 1,
    category: "React.js",
    link1: "https://krsteski-e-com.herokuapp.com",
    link2: "https://github.com/ikac0/e-com",
    icon1: "VIEW",
    icon2: "CODE",
    image: port1,
    title: "E-commerce",
    description: "Fully functional e-commerce site",
  },
  {
    id: 2,
    category: "React.js",
    link1: "http://krsteski-netflix.herokuapp.com/",
    link2: "https://github.com/ikac0/netflix",
    icon1: "VIEW",
    icon2: "CODE",
    image: port2,
    title: "Netflix Clone",
    description: "Cloned version of Netflix, with styled components",
  },
  {
    id: 3,
    category: "React.js",
    link1: "https://krsteski-todoist.herokuapp.com/",
    link2: "https://github.com/ikac0/todoist",
    icon1: "VIEW",
    icon2: "CODE",
    image: port4,
    title: "Todoist App Clone",
    description: "Cloned version of the popular Todoist App",
  },
  {
    id: 4,
    category: "React.js",
    link1: "http://krsteski-amazon.herokuapp.com/",
    link2: "https://github.com/ikac0/amazon-clone",
    icon1: "VIEW",
    icon2: "CODE",
    image: port3,
    title: "Amazon Clone",
    description: "Functional amazon based, e-commerce platform",
  },
  {
    id: 5,
    category: "JavaScript",
    link1: "",
    link2: "https://github.com/ikac0/budget-javascript",
    icon1: "VIEW",
    icon2: "CODE",
    image: port5,
    title: "Vanilla JavaScript Budget Calculator",
    description: "Expences tracker",
  },
  {
    id: 6,
    category: "React.js",
    link1: "",
    link2: "https://github.com/ikac0/pwa-react",
    icon1: "VIEW",
    icon2: "CODE",
    image: port5,
    title: "Simplest React PWA Weather App",
    description: "Very basic",
  },
  {
    id: 7,
    category: "kurac",
    link1: "",
    link2: "https://github.com/ikac0/budget-javascript",
    icon1: "VIEW",
    icon2: "CODE",
    image: port5,
    title: "Calculator",
    description: "Expences tracker",
  },
  {
    id: 8,
    category: "JavaScript",
    link1: "",
    link2: "https://github.com/ikac0/budget-javascript",
    icon1: "VIEW",
    icon2: "CODE",
    image: port5,
    title: "Javascript MovieTheatar",
    description: "Expences tracker",
  },
  {
    id: 9,
    category: "JavaScript",
    link1: "",
    link2: "https://github.com/ikac0/budget-javascript",
    icon1: "VIEW",
    icon2: "CODE",
    image: port5,
    title: "Vanilla JavaScript Lyrics finder",
    description: "Expences tracker",
  },
];

export default petProjects;
